### This is the 'secret environment variables template file (.secrets.tpl). It
### is used to create .secrets.env.  If you want that command to create something
### more or different then edit this file accordingly, erase .secrets.env, and
### run the secrets.zsh shell script file. That script will not include in the
### generated file the comments here beginning with "###".  All other lines will
### be included.
#
# --- NOTICE --->     Do not edit this file    <--- NOTICE ---
#
# This file (.secrets.env) was created by the secrets.zsh script using file
# .secrets.tpl as input.  You can (re)create it by running the .secrets.zsh
# script.  You must first erase this file (.secrets.env) though or that
# script will see it, assume all is well, and do noting.
#
# These environment variables are referenced in the build_flags section
# of platformio.ini of PlatformIO projects that use them in the code.
#

#
# For use by espota to authenticate ArduinoOTA.
#
export OTA_PASSWORD=\"op://dev/OTA/password\"

#
# Used by WiFi service to connect to the local WiFi network.
# 
export WIFI_SSID=\"op://dev/WiFi/username\"
export WIFI_PASSWORD=\"op://dev/WiFi/password\"
